		<div id="Meny">
			<div id="MenyLink1"><img src="images/design/spacer.gif" alt="" width="20" height="27" /><a href=".">Velkommen</a><br /></div>
			<div id="MenyLink2"><img src="images/design/spacer.gif" alt="" width="22" height="27" /><a href="omsoltoppen.asp">Om Soltoppen</a><br /></div>
			<div id="MenyLink3"><img src="images/design/spacer.gif" alt="" width="24" height="27" /><a href="soknadsskjema.asp">Søknadsskjema</a><br /></div>
			<div id="MenyLink4"><img src="images/design/spacer.gif" alt="" width="26" height="27" /><a href="foreldre.asp">Foreldresiden</a><br /></div>
			<div id="MenyLink5"><img src="images/design/spacer.gif" alt="" width="28" height="27" /><a href="kontakt.asp">Kontakt oss</a><br /></div>
			<!--<img src="images/design/spacer.gif" width="30" height="27" /><a href="vedtekter.asp" class="meny">Vedtekter</a><br />-->
		</div>