

			<div id="Header1" class="Header">Kontakt oss</div>
			<div id="ContentColumn1" class="ContentColumn">
	<h1>Kontaktinformasjon Soltoppen Barnehage </h1>
							<br />
	  &Aring;pningstider: 07:15 - 16:30 <br />
							  <br />
	
							<h1>Gateadresse:</h1><br />
						 
							Soltoppen Barnehage AS<br />
							Haneholmveien 126 <br />
							3209 Sandefjord<br />
							<br /> 
							<h1>Telefon: </h1><br />
							33 47 52 38<br />
							<br />
							<h1>Direkte til avdeling: </h1><br />
							90 54 47 37<br />
							<br />
							<h1>Direkte til kontor: </h1><br />
							48 12 29 55<br />
							<br />
							<h1>E-post adresse: </h1><br />
							<a href="mailto:post@soltoppenbarnehage.no">post@soltoppenbarnehage.no<br />
							<br />
							</a>
			</div>
			
			<div id="ContentColumn2" class="ContentColumn">
							<img src="images/haneholmveien126.jpg" width="300" height="223" alt="Soltoppen" />			
			</div>
			
