			<div id="Header1" class="Header">Om Soltoppen</div>
			<div id="ContentColumn1" class="ContentColumn">
			<h1>Om Soltoppen Barnehage AS </h1><br />
        	Soltoppen er en èn avdelings barnehage, med plass til ca 21  barn i alder 0-6 &aring;r. 
        	Soltoppen har et flott uteomr&aring;de.<br /><br />
	        Ved opptak av barn  vil vi sette opp barnegruppen, slik at det blir best mulig fordeling p&aring; alder  og kj&oslash;nn.
                V&aring;rt &oslash;nske er at  Soltoppen skal v&aelig;re et godt sted &aring; v&aelig;re for barn og voksne, der vi har respekt  for hverandre. Barna skal f&aring; oppleve n&aelig;rhet, trygghet og omsorg for sm&aring; og  store.<br /><br /><br />

<a href="images/CRW_5423.jpg" target="_blank"><img src="images/CRW_5423-s.jpg" width="300" height="199" alt="Soltoppen" /></a><br /><br /><br />

        <h1>&Aring;PNINGSTIDER  OG FRIDAGER.</h1>
        <ul>
                      <li>Barnehagen  &aring;pner kl 07.15 og stenger 16.30 hver dag.</li>
                      <li>Barnehagens  kjernetid er fra kl 09.30-13.30 hver dag.</li>
                      <li>Barnehagen holder stengt ved offentlige h&oslash;ytidsdager, samt lille julaften 23.12.</li>
                      <li>Barnehagen holder stengt onsdagen f&oslash;r skj&aelig;rtorsdag.</li>
                      <li>Barnehagen holder stengt i romjulen.</li>
                      <li>Barnehagen holder stengt i uke 29,30 og 31</li>
                      <li>Det er  lagt opp til 7 planleggingsdager i &aring;ret.</li>
                    </ul>
					
			</div>
			
			
			<div id="ContentColumn2" class="ContentColumn">
					  <a href="images/CRW_5406-1.jpg" target="_blank"><img src="images/CRW_5406-1-s.jpg" width="300" height="199" alt="Soltoppen" /></a>
                      <br /><br />
                      <h1>Eierforhold:</h1>
                      <br />
Barnehagens navn er  Soltoppen Barnehage AS og er privateid. 
                Eiere er Anne Kristine H Dalgleish og Kenneth Dalgleish. <br />
                      <br />
                      <h1>Form&aring;l</h1>
                      <ul>
                        <li>Barnehagen  drives til enhver tid etter lov om barnehager med forskrifter, rundskriv og  andre statlige vedtak og planer.</li>
                        <li>Barnehagen  skal s&oslash;rge for at alle barn har et godt milj&oslash; der lek og samv&aelig;r med andre barn  og voksne blir ivaretatt. Barnehagen skal i 			samarbeid med barnets hjem, bidra  til at barna utvikler evne til toleranse, omsorg for andre mennesker. Sikre lek  og l&aelig;ring i trygge og utfordrende omgivelser.</li>
                        <li>Barnehagen  drives i samv&aelig;r med rammeplan for barnehagen, &aring;rsplan og vedtekter for  barnehagen.</li>
                        <li>Lov om  internkontroll.</li>
                      </ul>
<a href="images/CRW_5405-4.jpg" target="_blank"><img src="images/CRW_5405-4-s.jpg" width="300" height="199" alt="Soltoppen" /></a>
			</div>